operations:
- message: creating neutron
- workflow: workflows/quark
  values:
    flavor: up
    color: red
- workflow: workflows/quark
  values:
    flavor: up
    color: green
- workflow: workflows/quark
  values:
    flavor: down
    color: blue
