operations:
- message: creating proton
- workflow: ../quark
  values:
    flavor: up
    color: red
- workflow: ../quark
  values:
    flavor: down
    color: green
- workflow: ../quark
  values:
    flavor: down
    color: blue
